export const EDIT_GUEST_ERROR = 'EDIT_GUEST_ERROR';
export const EDIT_GUEST_SUCCESS = 'EDIT_GUEST_SUCCESS';


export const GET_ATTENDEES_REQUEST = 'GET_ATTENDEES_REQUEST';
export const GET_ATTENDEES_SUCCESS = 'GET_ATTENDEES_SUCCESS';
export const GET_ATTENDEES_ERROR = 'GET_ATTENDEES_ERROR';

export const ADD_ATTENDEES_TO_EVENT = 'ADD_ATTENDEES_TO_EVENT';
export const ADD_ATTENDEES_TO_EVENT_ERROR = 'ADD_ATTENDEES_TO_EVENT_ERROR';
export const ADD_ATTENDEES_TO_EVENT_SUCCESS = 'ADD_ATTENDEES_TO_EVENT_SUCCESS';